# CodeRabbit Configuration
# Documentation: https://docs.coderabbit.ai/guides/configure-coderabbit

# Global Settings
language: "en-US"
early_access: false
data_retention: true

# Review Settings
reviews:
  # Set review profile to assertive for more detailed feedback
  profile: "chill"

  # Enable automatic reviews
  auto_review:
    enabled: true

  # Review all source code but exclude test files and documentation
  path_filters:
    - "!**/*.test.js"
    - "!**/*.test.ts"
    - "!**/*.spec.js"
    - "!**/*.spec.ts"
    - "!docs/**"
    - "!*.md"

  # Enable useful analysis tools
  # All tools are enabled by default, so we can use an empty configuration
  tools: {}

# Knowledge Base Settings
knowledge_base:
  # Keep review history for learning
  opt_out: false

# Code Generation Settings
code_generation:
  # Generate docstrings in English
  docstrings:
    language: "en-US"
