name: "Build and Push"
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v14
        with:
          name: dallas-college-lmic
          authToken: ${{secrets.CACHIX_AUTH_TOKEN}}
      - name: Build Docker image with Nix
        run: nix build .#docker
      - name: Load and push docker image
        run: |
          docker load < result
          docker tag spatial-jobs-index-api:latest ghcr.io/dallas-college-lmic/spatial-jobs-index-api:latest
          docker push ghcr.io/dallas-college-lmic/spatial-jobs-index-api:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/projects/spatial-jobs-index-api
            docker compose pull
            docker compose up -d
            sleep 10
            if curl -f -s http://localhost:8000/docs > /dev/null; then
              echo "✅ Deployment successful - API is responding"
            else
              echo "❌ Health check failed - API may not be running properly"
              docker compose logs --tail=20
              exit 1
            fi
            echo "🚀 Deployment completed successfully!"
