name: Build

# This workflow handles building artifacts after CI passes.
# Both frontend and backend must build successfully for the workflow to succeed.
# Built artifacts are cached in Cachix for the Deploy workflow to use.
# Runs on both pull requests and master branch pushes.

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  changes:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      nix: ${{ steps.filter.outputs.nix }}
      has-changes: ${{ steps.check-changes.outputs.has-changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # Compare against the parent commit for workflow_run events
          base: HEAD~1
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            nix:
              - 'flake.nix'
              - 'flake.lock'

      - name: Check if builds are needed
        id: check-changes
        run: |
          if [[ "${{ steps.filter.outputs.backend }}" == "true" || "${{ steps.filter.outputs.frontend }}" == "true" || "${{ steps.filter.outputs.nix }}" == "true" ]]; then
            echo "has-changes=true" >> $GITHUB_OUTPUT
          else
            echo "has-changes=false" >> $GITHUB_OUTPUT
          fi

  build-backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.nix == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: dallas-college-lmic
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build Docker image with Nix
        run: nix build .#backend-docker

      - name: Verify Docker image
        run: |
          docker load < result
          docker images | grep spatial-jobs-index-api

  build-frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' || needs.changes.outputs.nix == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: dallas-college-lmic
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build frontend with Nix
        run: nix build .#frontend

      - name: Verify build artifacts
        run: |
          ls -la result/
          test -f result/index.html
          test -f result/access_occupation.html
          test -f result/access_wagelvl.html
          test -f result/travel_time.html
